/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.68
 * Generated at: 2016-12-20 07:18:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.users;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"kr\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>login</title>\r\n");
      out.write("\r\n");
      out.write("<style rel=\"stylesheet\">\r\n");
      out.write("@charset \"UTF-8\";\r\n");
      out.write("@import url(https://fonts.googleapis.com/css?family=Lato:400,700);\r\n");
      out.write("* {\r\n");
      out.write("  -moz-box-sizing: border-box;\r\n");
      out.write("  -webkit-box-sizing: border-box;\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("  font-family: 'Lato', sans-serif;\r\n");
      out.write("  background-color: #f8f8f8;\r\n");
      out.write("}\r\n");
      out.write("body .container {\r\n");
      out.write("  position: relative;\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  width: 700px;\r\n");
      out.write("  height: 500px;\r\n");
      out.write("  margin: 80px auto 0;\r\n");
      out.write("  background-color: #ffffff;\r\n");
      out.write("  -moz-box-shadow: rgba(0, 0, 0, 0.1) 0px 10px 30px;\r\n");
      out.write("  -webkit-box-shadow: rgba(0, 0, 0, 0.1) 0px 10px 30px;\r\n");
      out.write("  box-shadow: rgba(0, 0, 0, 0.1) 0px 10px 30px;\r\n");
      out.write("}\r\n");
      out.write("body .container .half {\r\n");
      out.write("  float: left;\r\n");
      out.write("  width: 50%;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  padding: 58px 40px 0;\r\n");
      out.write("}\r\n");
      out.write("body .container .half.bg {\r\n");
      out.write("  background-image: url('/yousns/jsp/users/login.jpg');\r\n");
      out.write("  background-size: 400px;\r\n");
      out.write("  background-repeat: no-repeat;\r\n");
      out.write("}\r\n");
      out.write("body .container h1 {\r\n");
      out.write("  font-size: 18px;\r\n");
      out.write("  font-weight: 700;\r\n");
      out.write("  margin-bottom: 23px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-indent: 6px;\r\n");
      out.write("  letter-spacing: 7px;\r\n");
      out.write("  text-transform: uppercase;\r\n");
      out.write("  color: #263238;\r\n");
      out.write("}\r\n");
      out.write("body .container .tabs {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  margin-bottom: 29px;\r\n");
      out.write("  border-bottom: 1px solid #d9d9d9;\r\n");
      out.write("}\r\n");
      out.write("body .container .tabs .tab {\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  margin-bottom: -1px;\r\n");
      out.write("  padding: 20px 15px 10px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  letter-spacing: 0;\r\n");
      out.write("  border-bottom: 1px solid #d9d9d9;\r\n");
      out.write("  -moz-user-select: -moz-none;\r\n");
      out.write("  -ms-user-select: none;\r\n");
      out.write("  -webkit-user-select: none;\r\n");
      out.write("  user-select: none;\r\n");
      out.write("  transition: all 0.1s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("body .container .tabs .tab a {\r\n");
      out.write("  font-size: 11px;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  text-transform: uppercase;\r\n");
      out.write("  color: #d9d9d9;\r\n");
      out.write("  transition: all 0.1s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("body .container .tabs .tab.active a, body .container .tabs .tab:hover a {\r\n");
      out.write("  color: #263238;\r\n");
      out.write("}\r\n");
      out.write("body .container .tabs .tab.active {\r\n");
      out.write("  border-bottom: 1px solid #263238;\r\n");
      out.write("}\r\n");
      out.write("body .container .content form {\r\n");
      out.write("  position: relative;\r\n");
      out.write("  height: 287px;\r\n");
      out.write("}\r\n");
      out.write("body .container .content label:first-of-type, body .container .content input:first-of-type, body .container .content .more:first-of-type {\r\n");
      out.write("  -moz-animation: slideIn 0.4s cubic-bezier(0.37, 0.82, 0.2, 1);\r\n");
      out.write("  -webkit-animation: slideIn 0.4s cubic-bezier(0.37, 0.82, 0.2, 1);\r\n");
      out.write("  animation: slideIn 0.4s cubic-bezier(0.37, 0.82, 0.2, 1);\r\n");
      out.write("}\r\n");
      out.write("body .container .content label:nth-of-type(2), body .container .content input:nth-of-type(2), body .container .content .more:nth-of-type(2) {\r\n");
      out.write("  -moz-animation: slideIn 0.5s cubic-bezier(0.37, 0.82, 0.2, 1);\r\n");
      out.write("  -webkit-animation: slideIn 0.5s cubic-bezier(0.37, 0.82, 0.2, 1);\r\n");
      out.write("  animation: slideIn 0.5s cubic-bezier(0.37, 0.82, 0.2, 1);\r\n");
      out.write("}\r\n");
      out.write("body .container .content label:nth-of-type(3), body .container .content input:nth-of-type(3), body .container .content .more:nth-of-type(3) {\r\n");
      out.write("  -moz-animation: slideIn 0.6s cubic-bezier(0.37, 0.82, 0.2, 1);\r\n");
      out.write("  -webkit-animation: slideIn 0.6s cubic-bezier(0.37, 0.82, 0.2, 1);\r\n");
      out.write("  animation: slideIn 0.6s cubic-bezier(0.37, 0.82, 0.2, 1);\r\n");
      out.write("}\r\n");
      out.write("body .container .content label {\r\n");
      out.write("  font-size: 12px;\r\n");
      out.write("  color: #263238;\r\n");
      out.write("  -moz-user-select: -moz-none;\r\n");
      out.write("  -ms-user-select: none;\r\n");
      out.write("  -webkit-user-select: none;\r\n");
      out.write("  user-select: none;\r\n");
      out.write("}\r\n");
      out.write("body .container .content label:not([for='remember']) {\r\n");
      out.write("  display: none;\r\n");
      out.write("}\r\n");
      out.write("body .container .content input.inpt {\r\n");
      out.write("  font-size: 14px;\r\n");
      out.write("  display: block;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 42px;\r\n");
      out.write("  margin-bottom: 12px;\r\n");
      out.write("  padding: 16px 13px;\r\n");
      out.write("  color: #999999;\r\n");
      out.write("  border: 1px solid #d9d9d9;\r\n");
      out.write("  background: transparent;\r\n");
      out.write("  -moz-border-radius: 2px;\r\n");
      out.write("  -webkit-border-radius: 2px;\r\n");
      out.write("  border-radius: 2px;\r\n");
      out.write("}\r\n");
      out.write("body .container .content input.inpt::-webkit-input-placeholder {\r\n");
      out.write("  font-size: 14px;\r\n");
      out.write("  color: #999999;\r\n");
      out.write("  font-family: 'Lato', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("body .container .content input.inpt:-moz-placeholder {\r\n");
      out.write("  font-size: 14px;\r\n");
      out.write("  color: #999999;\r\n");
      out.write("  font-family: 'Lato', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("body .container .content input.inpt::-moz-placeholder {\r\n");
      out.write("  font-size: 14px;\r\n");
      out.write("  color: #999999;\r\n");
      out.write("  font-family: 'Lato', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("body .container .content input.inpt:-ms-input-placeholder {\r\n");
      out.write("  font-size: 14px;\r\n");
      out.write("  color: #999999;\r\n");
      out.write("  font-family: 'Lato', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("body .container .content input.inpt:focus {\r\n");
      out.write("  border-color: #999999;\r\n");
      out.write("}\r\n");
      out.write("body .container .content input.submit {\r\n");
      out.write("  font-size: 12px;\r\n");
      out.write("  line-height: 42px;\r\n");
      out.write("  display: block;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 42px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  vertical-align: middle;\r\n");
      out.write("  letter-spacing: 2px;\r\n");
      out.write("  text-transform: uppercase;\r\n");
      out.write("  color: #263238;\r\n");
      out.write("  border: 1px solid #263238;\r\n");
      out.write("  background: transparent;\r\n");
      out.write("  -moz-border-radius: 2px;\r\n");
      out.write("  -webkit-border-radius: 2px;\r\n");
      out.write("  border-radius: 2px;\r\n");
      out.write("}\r\n");
      out.write("body .container .content input.submit:hover {\r\n");
      out.write("  background-color: #263238;\r\n");
      out.write("  color: #ffffff;\r\n");
      out.write("  -moz-transition: all 0.2s;\r\n");
      out.write("  -o-transition: all 0.2s;\r\n");
      out.write("  -webkit-transition: all 0.2s;\r\n");
      out.write("  transition: all 0.2s;\r\n");
      out.write("}\r\n");
      out.write("body .container .content input:focus {\r\n");
      out.write("  outline: none;\r\n");
      out.write("}\r\n");
      out.write("body .container .content .checkbox {\r\n");
      out.write("  margin-top: 4px;\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  clip: rect(0 0 0 0);\r\n");
      out.write("  width: 0;\r\n");
      out.write("  height: 0;\r\n");
      out.write("  margin: 17px -1px;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  border: 0;\r\n");
      out.write("}\r\n");
      out.write("body .container .content .checkbox + label {\r\n");
      out.write("  vertical-align: middle;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  width: 50%;\r\n");
      out.write("}\r\n");
      out.write("body .container .content .checkbox + label:before {\r\n");
      out.write("  content: \"\\A\";\r\n");
      out.write("  color: #999999;\r\n");
      out.write("  font-family: Verdana;\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("  font-size: 8px;\r\n");
      out.write("  line-height: 10px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  vertical-align: middle;\r\n");
      out.write("  position: relative;\r\n");
      out.write("  -moz-border-radius: 2px;\r\n");
      out.write("  -webkit-border-radius: 2px;\r\n");
      out.write("  border-radius: 2px;\r\n");
      out.write("  background: transparent;\r\n");
      out.write("  border: 1px solid #d9d9d9;\r\n");
      out.write("  width: 11px;\r\n");
      out.write("  height: 11px;\r\n");
      out.write("  margin: -2px 8px 0 0;\r\n");
      out.write("}\r\n");
      out.write("body .container .content .checkbox:checked + label:before {\r\n");
      out.write("  /* content: \"â\"; */\r\n");
      out.write("  content:\"**\";\r\n");
      out.write("}\r\n");
      out.write("body .container .content .submit-wrap {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  bottom: 0;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("}\r\n");
      out.write("body .container .content .submit-wrap a {\r\n");
      out.write("  font-size: 12px;\r\n");
      out.write("  display: block;\r\n");
      out.write("  margin-top: 20px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  color: #999999;\r\n");
      out.write("}\r\n");
      out.write("body .container .content .submit-wrap a:hover {\r\n");
      out.write("  text-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("body .container .content .signup-cont {\r\n");
      out.write("  display: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@keyframes slideIn {\r\n");
      out.write("  0% {\r\n");
      out.write("    filter: progid:DXImageTransform.Microsoft.Alpha(Opacity=0);\r\n");
      out.write("    opacity: 0;\r\n");
      out.write("    margin-left: -320px;\r\n");
      out.write("  }\r\n");
      out.write("  100% {\r\n");
      out.write("    filter: progid:DXImageTransform.Microsoft.Alpha(enabled=false);\r\n");
      out.write("    opacity: 1;\r\n");
      out.write("    margin-left: 0px;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("@-webkit-keyframes slideIn {\r\n");
      out.write("  0% {\r\n");
      out.write("    filter: progid:DXImageTransform.Microsoft.Alpha(Opacity=0);\r\n");
      out.write("    opacity: 0;\r\n");
      out.write("    margin-left: -320px;\r\n");
      out.write("  }\r\n");
      out.write("  100% {\r\n");
      out.write("    filter: progid:DXImageTransform.Microsoft.Alpha(enabled=false);\r\n");
      out.write("    opacity: 1;\r\n");
      out.write("    margin-left: 0px;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write(".credits {\r\n");
      out.write("  display: block;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  right: 0;\r\n");
      out.write("  bottom: 0;\r\n");
      out.write("  color: #999999;\r\n");
      out.write("  font-size: 14px;\r\n");
      out.write("  margin: 0 10px 10px 0;\r\n");
      out.write("}\r\n");
      out.write(".credits a {\r\n");
      out.write("  filter: progid:DXImageTransform.Microsoft.Alpha(Opacity=80);\r\n");
      out.write("  opacity: 0.8;\r\n");
      out.write("  color: inherit;\r\n");
      out.write("  font-weight: 700;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<section class=\"container\">\r\n");
      out.write("\t<article class=\"half\">\r\n");
      out.write("\t    <h1>YouStar</h1>\r\n");
      out.write("\t        <div class=\"tabs\">\r\n");
      out.write("\t            <span class=\"tab signin active\">\r\n");
      out.write("\t            \t<a href=\"#signin\">Sign in</a>\r\n");
      out.write("            \t</span>\r\n");
      out.write("\t            <span class=\"tab signup\">\r\n");
      out.write("\t            \t<a href=\"#signup\">Sign up</a>\r\n");
      out.write("            \t</span>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"content\">\r\n");
      out.write("\t            <div class=\"signin-cont cont\">\r\n");
      out.write("\t                <form action=\"users/auth\" method=\"POST\">\r\n");
      out.write("\t                    <label for=\"id\">Your ID</label>\r\n");
      out.write("\t                    \t<input type=\"email\" name=\"id\" id=\"id\" class=\"inpt\" required=\"required\" placeholder=\"Your ID(email)\">\r\n");
      out.write("\t                    <label for=\"password\">Your password</label>\r\n");
      out.write("\t\t                    <input type=\"password\" name=\"password\" id=\"password\" class=\"inpt\" required=\"required\" placeholder=\"Your password\">\r\n");
      out.write("\t                    <div class=\"submit-wrap\">\r\n");
      out.write("\t                        <input type=\"submit\" value=\"Sign in\" class=\"submit\">\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t\t\t        </form>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t        <div class=\"signup-cont cont\">\r\n");
      out.write("                <form action=\"users\" method=\"post\">\r\n");
      out.write("                    <label for=\"id\">Your ID</label>\r\n");
      out.write("                   \t\t<input type=\"email\" name=\"id\" id=\"id\" class=\"inpt\" required=\"required\" placeholder=\"Your ID(email)\">\r\n");
      out.write("                    <label for=\"name\">Your name</label>\r\n");
      out.write("                    \t<input type=\"text\" name=\"name\" id=\"name\" class=\"inpt\" required=\"required\" placeholder=\"Your name\">\r\n");
      out.write("                    <label for=\"password\">Your password</label> \r\n");
      out.write("                    \t<input type=\"password\" name=\"password\" id=\"password\" class=\"inpt\" required=\"required\" placeholder=\"Your password\">\r\n");
      out.write("                \t<label for=\"gender\">Your gender</label>\t\t\t\t\t   \r\n");
      out.write("    \t\t\t\t\t<input type=\"radio\" name=\"gender\" class=\"radio\" value=\"0\">man\r\n");
      out.write("    \t\t\t\t\t<input type=\"radio\" name=\"gender\" class=\"radio\" value=\"1\">woman \r\n");
      out.write("\t\t\t\t\t<div class=\"submit-wrap\">\r\n");
      out.write("\t\t\t           \t<input type=\"submit\" value=\"Sign up\" class=\"submit\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("        \t\t</form>\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</article>\r\n");
      out.write("\t\t    <div class=\"half bg\"></div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script> \r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$('.tabs .tab').click(function(){\r\n");
      out.write("    if ($(this).hasClass('signin')) {\r\n");
      out.write("        $('.tabs .tab').removeClass('active');\r\n");
      out.write("        $(this).addClass('active');\r\n");
      out.write("        $('.cont').hide();\r\n");
      out.write("        $('.signin-cont').show();\r\n");
      out.write("    } \r\n");
      out.write("    if ($(this).hasClass('signup')) {\r\n");
      out.write("        $('.tabs .tab').removeClass('active');\r\n");
      out.write("        $(this).addClass('active');\r\n");
      out.write("        $('.cont').hide();\r\n");
      out.write("        $('.signup-cont').show();\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
