/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.68
 * Generated at: 2016-12-20 07:18:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.users;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.yousns.vo.UserVO;

public final class mypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/jsp/users/../header.jsp", Long.valueOf(1481878627836L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<title>YouStar</title>\r\n");
      out.write("<link  href=\"\\yousns\\jsp\\style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("#wrap {\r\n");
      out.write("\tdisplay: table;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#cell {\r\n");
      out.write("\tdisplay: table-cell;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"d4\">\r\n");
      out.write("\t\t<form action=\"/yousns/search\" method=\"POST\">\r\n");
      out.write("\t\t\t<input type=\"text\" placeholder=\"검색어 입력\" name=\"keyword\">\r\n");
      out.write("\t\t\t<button type=\"submit\"></button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Modal -->\r\n");
      out.write("\t<div class=\"modal fade\" id=\"reportComment\" role=\"dialog\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Modal content-->\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<form method=\"post\" action=\"/\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"modal-title\">댓글 신고</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t<textarea class=\"autosize\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"border: 1px solid #d2d2d2; width: 100%;\" name=\"content\"></textarea>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-default\" data-dismiss=\"modal\">전송</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Modal -->\r\n");
      out.write("\t<div class=\"modal fade\" id=\"reportPost\" role=\"dialog\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Modal content-->\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<form method=\"post\" action=\"/\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"modal-title\">게시글 신고</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t<textarea class=\"autosize\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"border: 1px solid #d2d2d2; width: 100%;\" name=\"content\"></textarea>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-default\" data-dismiss=\"modal\">전송</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"sidebar\">\r\n");
      out.write("\t\t<h1 class=\"blog-title\">\r\n");
      out.write("\t\t\t<a href=\"/yousns/posts\" title=\"You Star\" rel=\"home\"><img\r\n");
      out.write("\t\t\t\tsrc=\"\\yousns\\jsp\\image\\logo.png\" width=\"180px\"></a>\r\n");
      out.write("\t\t</h1>\r\n");
      out.write("\r\n");
      out.write("\t\t<a class=\"nav-toggle hidden\" title=\"Click to view the navigation\"\r\n");
      out.write("\t\t\thref=\"#\">\r\n");
      out.write("\t\t\t<div class=\"bars\">\r\n");
      out.write("\t\t\t\t<div class=\"bar\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"bar\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"bar\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span class=\"menu\">Menu</span> <span class=\"close\">Close</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t<ul class=\"main-menu\">\r\n");
      out.write("\t\t\t<li\r\n");
      out.write("\t\t\t\tclass=\"menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-66 current_page_item menu-item-68\"><a\r\n");
      out.write("\t\t\t\thref=\"/yousns/posts\">HOME</a></li>\r\n");
      out.write("\t\t\t<li\r\n");
      out.write("\t\t\t\tclass=\"menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-163\"><a\r\n");
      out.write("\t\t\t\thref=\"/yousns/users/");
      out.print(session.getAttribute("userKey"));
      out.write("/friends\">FRIEND</a>\r\n");
      out.write("\t\t\t\t<ul class=\"sub-menu\">\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li\r\n");
      out.write("\t\t\t\tclass=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-37\"><a\r\n");
      out.write("\t\t\t\thref=\"/yousns/posts\">POST</a></li>\r\n");
      out.write("\t\t\t<li\r\n");
      out.write("\t\t\t\tclass=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-43\"><a\r\n");
      out.write("\t\t\t\thref=\"/yousns/pages\">PAGE</a>\r\n");
      out.write("\t\t\t\t<ul class=\"sub-menu\">\r\n");
      out.write("\t\t\t\t\t<li\r\n");
      out.write("\t\t\t\t\t\tclass=\"menu-item menu-item-type-post_type menu-item-object-page menu-item-86\"><a\r\n");
      out.write("\t\t\t\t\t\thref=\"/yousns/users/");
      out.print(session.getAttribute("userKey"));
      out.write("\">MYPAGE</a></li>\r\n");
      out.write("\t\t\t\t\t<li\r\n");
      out.write("\t\t\t\t\t\tclass=\"menu-item menu-item-type-post_type menu-item-object-page menu-item-86\"><a\r\n");
      out.write("\t\t\t\t\t\thref=\"/yousns/users/");
      out.print(session.getAttribute("userKey"));
      out.write("/details\">DETAILS</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li\r\n");
      out.write("\t\t\t\tclass=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-45\"><a\r\n");
      out.write("\t\t\t\thref=\"/yousns/groups\">GROUP</a>\r\n");
      out.write("\t\t\t<li\r\n");
      out.write("\t\t\t\tclass=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-45\"><a\r\n");
      out.write("\t\t\t\thref=\"/yousns/users/auth/out\">LOGOUT</a>\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<div class=\"widgets\"></div>\r\n");
      out.write("\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /sidebar -->");
      out.write("\r\n");
      out.write("<!-- body -->\r\n");
      com.yousns.dao.UserDAO userDAO = null;
      userDAO = (com.yousns.dao.UserDAO) _jspx_page_context.getAttribute("userDAO", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (userDAO == null){
        userDAO = new com.yousns.dao.UserDAO();
        _jspx_page_context.setAttribute("userDAO", userDAO, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write(">\r\n");
      out.write("\r\n");

	String userkey = (String)session.getAttribute("userKey");
	UserVO vo = userDAO.myPage(userkey);
	

      out.write("\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("   <div class=\"content2\">\r\n");
      out.write("      <img src=\"\\yousns\\jsp\\image\\mypage.png\" width=\"40px\" height=\"40px\"\r\n");
      out.write("         style=\"padding-bottom: 0px;\"><span\r\n");
      out.write("         style=\"font-size: 20pt; margin: 0px 5px 0px 5px; color: #38baeb; padding-bottom: 2px;\"><strong>마이\r\n");
      out.write("            페이지</strong></span>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("   <div class=\"content3\" style=\"background:#fff; padding-bottom:0px\">\r\n");
      out.write("      <div class=\"left-info\">\r\n");
      out.write("         <div class=\"infoform\">\r\n");
      out.write("            <div class=\"infophoto\" style='display: table-cell; vertical-align: middle'>\r\n");
      out.write("               E-Mail\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"infoname\"\r\n");
      out.write("               style='display: table-cell; vertical-align: middle'>\r\n");
      out.write("               <strong>");
      out.print(vo.getEmail());
      out.write("</strong>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"left-info\">\r\n");
      out.write("         <div class=\"infoform\">\r\n");
      out.write("            <div class=\"infophoto\">\r\n");
      out.write("               Name\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"infoname\">\r\n");
      out.write("               <strong>");
      out.print(vo.getName() );
      out.write("</strong>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"left-info\">\r\n");
      out.write("         <div class=\"infoform\">\r\n");
      out.write("            <div class=\"infophoto\">\r\n");
      out.write("               Password\r\n");
      out.write("            </div>\r\n");
      out.write("            <form action=\"/yousns/users/");
      out.print(vo.getUserKey());
      out.write("/edit\" method=\"post\" >\r\n");
      out.write("            <div class=\"infoname\"\r\n");
      out.write("               style='display: table-cell; vertical-align: middle'>\r\n");
      out.write("               <strong><input size=\"20\" name=\"Pwd\" type=\"text\" placeholder=\"********\" style=\"text-align=left;\"></strong>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"infobtn\">\r\n");
      out.write("            \t\r\n");
      out.write("              \t\t<button type=\"submit\" style=\"background-color: white\"><img src=\"\\yousns\\jsp\\image\\change.png\" width=\"50px\" height=\"35px\"></button> \r\n");
      out.write("              \r\n");
      out.write("            </div>\r\n");
      out.write("             </form>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"left-info\">\r\n");
      out.write("         <div class=\"infoform\">\r\n");
      out.write("            <div class=\"infophoto\">\r\n");
      out.write("               Gender\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"infoname\">\r\n");
      out.write("               ");
      out.print(vo.getGender()==0?"남":"여");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
