/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.68
 * Generated at: 2016-12-20 07:18:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.posts;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.yousns.vo.FriendVO;
import com.yousns.vo.UserVO;
import com.yousns.vo.GroupVO;
import com.yousns.vo.PageVO;
import com.yousns.vo.PostVO;
import java.util.ArrayList;

public final class posts_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/jsp/posts/../header.jsp", Long.valueOf(1481878627836L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<title>YouStar</title>\r\n");
      out.write("<link  href=\"\\yousns\\jsp\\style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("#wrap {\r\n");
      out.write("\tdisplay: table;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#cell {\r\n");
      out.write("\tdisplay: table-cell;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"d4\">\r\n");
      out.write("\t\t<form action=\"/yousns/search\" method=\"POST\">\r\n");
      out.write("\t\t\t<input type=\"text\" placeholder=\"검색어 입력\" name=\"keyword\">\r\n");
      out.write("\t\t\t<button type=\"submit\"></button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Modal -->\r\n");
      out.write("\t<div class=\"modal fade\" id=\"reportComment\" role=\"dialog\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Modal content-->\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<form method=\"post\" action=\"/\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"modal-title\">댓글 신고</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t<textarea class=\"autosize\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"border: 1px solid #d2d2d2; width: 100%;\" name=\"content\"></textarea>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-default\" data-dismiss=\"modal\">전송</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Modal -->\r\n");
      out.write("\t<div class=\"modal fade\" id=\"reportPost\" role=\"dialog\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Modal content-->\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<form method=\"post\" action=\"/\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"modal-title\">게시글 신고</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t<textarea class=\"autosize\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"border: 1px solid #d2d2d2; width: 100%;\" name=\"content\"></textarea>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-default\" data-dismiss=\"modal\">전송</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"sidebar\">\r\n");
      out.write("\t\t<h1 class=\"blog-title\">\r\n");
      out.write("\t\t\t<a href=\"/yousns/posts\" title=\"You Star\" rel=\"home\"><img\r\n");
      out.write("\t\t\t\tsrc=\"\\yousns\\jsp\\image\\logo.png\" width=\"180px\"></a>\r\n");
      out.write("\t\t</h1>\r\n");
      out.write("\r\n");
      out.write("\t\t<a class=\"nav-toggle hidden\" title=\"Click to view the navigation\"\r\n");
      out.write("\t\t\thref=\"#\">\r\n");
      out.write("\t\t\t<div class=\"bars\">\r\n");
      out.write("\t\t\t\t<div class=\"bar\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"bar\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"bar\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span class=\"menu\">Menu</span> <span class=\"close\">Close</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t<ul class=\"main-menu\">\r\n");
      out.write("\t\t\t<li\r\n");
      out.write("\t\t\t\tclass=\"menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-66 current_page_item menu-item-68\"><a\r\n");
      out.write("\t\t\t\thref=\"/yousns/posts\">HOME</a></li>\r\n");
      out.write("\t\t\t<li\r\n");
      out.write("\t\t\t\tclass=\"menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-163\"><a\r\n");
      out.write("\t\t\t\thref=\"/yousns/users/");
      out.print(session.getAttribute("userKey"));
      out.write("/friends\">FRIEND</a>\r\n");
      out.write("\t\t\t\t<ul class=\"sub-menu\">\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li\r\n");
      out.write("\t\t\t\tclass=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-37\"><a\r\n");
      out.write("\t\t\t\thref=\"/yousns/posts\">POST</a></li>\r\n");
      out.write("\t\t\t<li\r\n");
      out.write("\t\t\t\tclass=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-43\"><a\r\n");
      out.write("\t\t\t\thref=\"/yousns/pages\">PAGE</a>\r\n");
      out.write("\t\t\t\t<ul class=\"sub-menu\">\r\n");
      out.write("\t\t\t\t\t<li\r\n");
      out.write("\t\t\t\t\t\tclass=\"menu-item menu-item-type-post_type menu-item-object-page menu-item-86\"><a\r\n");
      out.write("\t\t\t\t\t\thref=\"/yousns/users/");
      out.print(session.getAttribute("userKey"));
      out.write("\">MYPAGE</a></li>\r\n");
      out.write("\t\t\t\t\t<li\r\n");
      out.write("\t\t\t\t\t\tclass=\"menu-item menu-item-type-post_type menu-item-object-page menu-item-86\"><a\r\n");
      out.write("\t\t\t\t\t\thref=\"/yousns/users/");
      out.print(session.getAttribute("userKey"));
      out.write("/details\">DETAILS</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li\r\n");
      out.write("\t\t\t\tclass=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-45\"><a\r\n");
      out.write("\t\t\t\thref=\"/yousns/groups\">GROUP</a>\r\n");
      out.write("\t\t\t<li\r\n");
      out.write("\t\t\t\tclass=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-45\"><a\r\n");
      out.write("\t\t\t\thref=\"/yousns/users/auth/out\">LOGOUT</a>\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<div class=\"widgets\"></div>\r\n");
      out.write("\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /sidebar -->");
      out.write("\r\n");
      out.write("\r\n");
      com.yousns.dao.PostDAO postDAO = null;
      postDAO = (com.yousns.dao.PostDAO) _jspx_page_context.getAttribute("postDAO", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (postDAO == null){
        postDAO = new com.yousns.dao.PostDAO();
        _jspx_page_context.setAttribute("postDAO", postDAO, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      com.yousns.dao.UserDAO userDAO = null;
      userDAO = (com.yousns.dao.UserDAO) _jspx_page_context.getAttribute("userDAO", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (userDAO == null){
        userDAO = new com.yousns.dao.UserDAO();
        _jspx_page_context.setAttribute("userDAO", userDAO, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      com.yousns.dao.PageDAO pageDAO = null;
      pageDAO = (com.yousns.dao.PageDAO) _jspx_page_context.getAttribute("pageDAO", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (pageDAO == null){
        pageDAO = new com.yousns.dao.PageDAO();
        _jspx_page_context.setAttribute("pageDAO", pageDAO, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      com.yousns.dao.GroupDAO groupDAO = null;
      groupDAO = (com.yousns.dao.GroupDAO) _jspx_page_context.getAttribute("groupDAO", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (groupDAO == null){
        groupDAO = new com.yousns.dao.GroupDAO();
        _jspx_page_context.setAttribute("groupDAO", groupDAO, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("<script src=\"//code.jquery.com/jquery.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$(\"textarea.autosize\").keyup(\r\n");
      out.write("\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t$(this).css(\"height\", \"1px\").css(\"height\",\r\n");
      out.write("\t\t\t\t\t\t\t(20 + $(this).prop(\"scrollHeight\")) + \"px\");\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");

	String userkey = (String) session.getAttribute("userKey");
	String someone = (String) request.getAttribute("someonekey");
	String pagekey = (String) request.getAttribute("pagekey");
	String groupkey = (String) request.getAttribute("groupkey");
	PageVO pageinfo = null;
	GroupVO groupinfo = null;
	ArrayList<PostVO> posts = null;

	if (someone != null) {
		posts = userDAO.getMyPosts(someone);
		UserVO u = userDAO.myPage(someone);
		ArrayList<FriendVO> myflist = userDAO.getfriends(userkey);
		ArrayList<String> fklist=new ArrayList<String>();
		for(FriendVO v : myflist){
			fklist.add(v.getFriendKey());
		}
		u.setPwd(null);

      out.write("\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("\t<div class=\"content2\">\r\n");
      out.write("\t\t<img src=\"\\yousns\\jsp\\image\\page.png\" width=\"30px\" height=\"30px\"\r\n");
      out.write("\t\t\tstyle=\"padding-bottom: 0px;\"><span\r\n");
      out.write("\t\t\tstyle=\"font-size: 20pt; margin: 5px 5px 0px 5px; color: #38baeb; padding-bottom: 2px;\">\r\n");
      out.write("\t\t\t<strong>");
      out.print(u.getName());
      out.write("</strong>\r\n");
      out.write("\t\t</span>\r\n");
      out.write("\t\t");

			if (!fklist.contains(someone) && !someone.equals(userkey)) {
		
      out.write("\r\n");
      out.write("\t\t<a\r\n");
      out.write("\t\t\thref=\"/yousns/users/");
      out.print(session.getAttribute("userKey"));
      out.write("/friends/");
      out.print(someone);
      out.write("\">\r\n");
      out.write("\t\t\t친구신청 </a>\r\n");
      out.write("\t\t");

			}
		
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");

	} else if (pagekey != null) {
		posts = pageDAO.getnewspeed(pagekey);
		pageinfo = pageDAO.read_page(pagekey);

      out.write("\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("\t<div class=\"content2\">\r\n");
      out.write("\t\t<img src=\"\\yousns\\jsp\\image\\page.png\" width=\"30px\" height=\"30px\"\r\n");
      out.write("\t\t\tstyle=\"padding-bottom: 0px;\"><span\r\n");
      out.write("\t\t\tstyle=\"font-size: 20pt; margin: 5px 5px 0px 5px; color: #38baeb; padding-bottom: 2px;\">\r\n");
      out.write("\t\t\t<strong>");
      out.print(pageinfo.getPageName());
      out.write("</strong>\r\n");
      out.write("\t\t</span>\r\n");
      out.write("\t\t<p style=\"margin: 5px 5px 0px 5px; padding-bottom: 2px;\">");
      out.print(pageinfo.getSubscribe_cnt());
      out.write("\r\n");
      out.write("\t\t\t명 구독중\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<a href=\"/yousns/pages/");
      out.print(pageinfo.getPageKey());
      out.write("/users/");
      out.print(userkey);
      out.write("\">\r\n");
      out.write("\t\t\t<p style=\"margin: 5px 5px 0px 5px; padding-bottom: 2px;\">구독하기</p>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");

	} else if (groupkey != null) {
		posts = groupDAO.getnewspeed(groupkey);
		groupinfo = groupDAO.read_group(groupkey);
		ArrayList<FriendVO> mlist = groupDAO.list_member(groupkey);

      out.write("\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("\t<div class=\"content2\">\r\n");
      out.write("\t\t<img src=\"\\yousns\\jsp\\image\\page.png\" width=\"30px\" height=\"30px\"\r\n");
      out.write("\t\t\tstyle=\"padding-bottom: 0px;\"><span\r\n");
      out.write("\t\t\tstyle=\"font-size: 20pt; margin: 5px 5px 0px 5px; color: #38baeb; padding-bottom: 2px;\">\r\n");
      out.write("\t\t\t<strong>");
      out.print(groupinfo.getGroupName());
      out.write("</strong>\r\n");
      out.write("\t\t</span>\r\n");
      out.write("\t\t<p style=\"margin: 5px 5px 0px 5px; padding-bottom: 2px;\">");
      out.print(groupinfo.getMembers_cnt());
      out.write("\r\n");
      out.write("\t\t\t명 가입\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<a href=\"/yousns/groups/");
      out.print(groupinfo.getGroupKey());
      out.write("/users\">구성원보기\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t");

			if (groupinfo.getUserKey().equals(userkey)) {
		
      out.write("\r\n");
      out.write("\t\t<a href=\"/yousns/groups/");
      out.print(groupinfo.getGroupKey());
      out.write("/delete\">삭제하기</a>\r\n");
      out.write("\t\t<a href=\"/yousns/groups/");
      out.print(groupinfo.getGroupKey());
      out.write("/requests\">가입요청현황</a>\r\n");
      out.write("\t\t");

			} else {
					boolean isMember = false;
					for (FriendVO m : mlist) {
						if (m.getFriendKey().equals(userkey))
							isMember = true;
					}
					if (isMember) {
		
      out.write("\r\n");
      out.write("\t\t<a href=\"/yousns/groups/");
      out.print(groupinfo.getGroupKey());
      out.write("/users/");
      out.print(userkey);
      out.write("/delete\">\r\n");
      out.write("\t\t\t<p style=\"margin: 5px 5px 0px 5px; padding-bottom: 2px;\">탈퇴하기</p>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t");

			} else {
		
      out.write("<a href=\"/yousns/groups/");
      out.print(groupinfo.getGroupKey());
      out.write("/users/");
      out.print(userkey);
      out.write("\">\r\n");
      out.write("\t\t\t<p style=\"margin: 5px 5px 0px 5px; padding-bottom: 2px;\">가입하기</p>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t");
}}
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");

	
	} else {
		posts = postDAO.getlist(userkey);
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!— 게시글 작성 —>\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("\t<div class=\"content\">\r\n");
      out.write("\t\t<div class=\"photospace\">\r\n");
      out.write("\t\t\t<img alt=\"person\" src=\"/yousns/jsp/image/person.png\" width=\"100%\"\r\n");
      out.write("\t\t\t\theight=\"100%\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"stringspace\">\r\n");
      out.write("\t\t\t<a href=\"/yousns/users/");
      out.print(userkey);
      out.write("/posts\"><span style=\"margin: 0 0 5% 1%;\">");
      out.print((String) session.getAttribute("userName"));
      out.write("\r\n");
      out.write("\t\t\t\t<br> </span></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<form action=\"/yousns/posts\" method=\"POST\"\r\n");
      out.write("\t\t\tstyle=\"width: 90%; margin-left: 9%; margin-top: 3.3012%;\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"pageKey\"\r\n");
      out.write("\t\t\t\tvalue=\"");
      out.print(pageinfo != null ? pageinfo.getPageKey() : "");
      out.write("\"> <input\r\n");
      out.write("\t\t\t\ttype=\"hidden\" name=\"groupKey\"\r\n");
      out.write("\t\t\t\tvalue=\"");
      out.print(groupinfo != null ? groupinfo.getGroupKey() : "");
      out.write("\"> <input\r\n");
      out.write("\t\t\t\tclass=\"autosize\" type=\"text\" name=\"utubeLink\"\r\n");
      out.write("\t\t\t\tplaceholder=\"  유투브 링크 입력\" style=\"margin-bottom: 1%; width: 80%;\">\r\n");
      out.write("\t\t\t<textarea class=\"autosize\" rows=\"5\" name=\"content\"\r\n");
      out.write("\t\t\t\tplaceholder=\"무슨 동영상을 공유하고 싶은가요?\"\r\n");
      out.write("\t\t\t\tstyle=\"border-bottom: 1px solid #d2d2d2; width: 80%;\"></textarea>\r\n");
      out.write("\t\t\t<button type=\"submit\">\r\n");
      out.write("\t\t\t\t<img alt=\"submit\" src=\"\\yousns\\jsp\\image\\post.png\" width=\"62px\"\r\n");
      out.write("\t\t\t\t\theight=\"45px\">\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");

	if (posts != null) {
		for (PostVO vo : posts) {

      out.write("\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("\t<div class=\"content\">\r\n");
      out.write("\t\t<div class=\"photospace\">\r\n");
      out.write("\t\t\t<img alt=\"person\" src=\"/yousns/jsp/image/person.png\" width=\"100%\"\r\n");
      out.write("\t\t\t\theight=\"100%\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"stringspace\">\r\n");
      out.write("\t\t\t<a href=\"/yousns/users/");
      out.print(vo.getUserKey());
      out.write("/posts\"><span style=\"margin: 0 0 5% 3%;\"> ");
      out.print(vo.getName());
      out.write(" <br>\r\n");
      out.write("\t\t\t</span></a>\r\n");
      out.write("\t\t\t");
if(vo.getGroupkey() !=null) {
      out.write("\r\n");
      out.write("\t\t\t<a href=\"/yousns/groups/");
      out.print(vo.getGroupkey());
      out.write("\"><span style=\"margin: 0 0 5% 3%;\"> ");
      out.print(vo.getGroupname());
      out.write(" <br>\r\n");
      out.write("\t\t\t</span></a>\r\n");
      out.write("\t\t\t");
}else if(vo.getPagekey() !=null){
      out.write("\r\n");
      out.write("\t\t\t<a href=\"/yousns/pages/");
      out.print(vo.getPagekey());
      out.write("\"><span style=\"margin: 0 0 5% 3%;\"> ");
      out.print(vo.getPagename());
      out.write(" <br>\r\n");
      out.write("\t\t\t</span></a>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"datespace\" style=\"margin-left: 9%;\">");
      out.print(vo.getDate());
      out.write(" \r\n");
      out.write("\t\t");
if(vo.getUserKey().equals(userkey)){ 
      out.write("\r\n");
      out.write("\t\t<span><a href=\"/yousns/posts/");
      out.print(vo.getPostKey());
      out.write("/delete\">삭제하기</a></span>\r\n");
      out.write("\t\t");
} 
      out.write("</div>\r\n");
      out.write("\t\t<iframe width=\"73%\" height=\"480px\" src=\"");
      out.print(vo.getUtubeLink());
      out.write("\"\r\n");
      out.write("\t\t\tframeborder=\"0\" allowfullscreen style=\"margin: 6% 10% 0 2.04%;\">\r\n");
      out.write("\t\t</iframe>\r\n");
      out.write("\t\t<textarea class=\"autosize\"\r\n");
      out.write("\t\t\tstyle=\"border: 0px solid #d2d2d2; width: 73%; margin-left: 0%;\">");
      out.print(vo.getContent());
      out.write("</textarea>\r\n");
      out.write("\t\t<div class=\"postbtn\" >\r\n");
      out.write("\t\t\t<a href=\"posts/");
      out.print(vo.getPostKey());
      out.write("/likes\"\r\n");
      out.write("\t\t\t\tstyle=\"text-align: right; width: auto; height: 40px;\">\r\n");
      out.write("\t\t\t\t<button type=\"submit\" style=\"background-color: white\">\r\n");
      out.write("\t\t\t\t\t<img alt=\"like\" src=\"\\yousns\\jsp\\image\\like.png\" width=\"50px\"\r\n");
      out.write("\t\t\t\t\t\theight=\"50px\"><span style=\"font-size: 70%; color: #F15B42;\">\r\n");
      out.write("\t\t\t\t\t\t<strong> ");
      out.print(vo.getLike_cnt());
      out.write("</strong>\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<a href=\"posts/");
      out.print(vo.getPostKey());
      out.write("\">\r\n");
      out.write("\t\t\t\t<button type=\"submit\" style=\"background-color: white\">\r\n");
      out.write("\t\t\t\t\t<img alt=\"comment\" src=\"\\yousns\\jsp\\image\\comment.png\" width=\"50px\"\r\n");
      out.write("\t\t\t\t\t\theight=\"50px\"><span style=\"font-size: 70%; color: #F15B42;\">\r\n");
      out.write("\t\t\t\t\t\t<strong> ");
      out.print(vo.getComment_cnt());
      out.write("</strong>\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<button style=\"background-color: white\">\r\n");
      out.write("\t\t\t\t<img alt=\"report\" src=\"\\yousns\\jsp\\image\\report.png\" width=\"50px\"\r\n");
      out.write("\t\t\t\t\theight=\"50px\" data-toggle=\"modal\" data-target=\"#reportPost\">\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");

	}
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
